replicaCount: 1
namespace: "frontend"

image:
  repository: saurabhred
  name: frontend-nginx
  tag: 0.1.2

ports:
  port: 80
  targetPort: 80
  protocol: TCP
  nodePort: 30098

service:
  type: NodePort

labels:
  app: nginx
  tier: frontend
  env: test

serviceAccount:
  enabled: true
  name: frontend-sa
  resources: ["apps", "services", "deployments", "pods"]
  actions: ["list", "get", "apply", "patch"]

volumes:
  enabled: false
  mountPathName: frontend-data
  pv: frontend-pv
  pvc: frontend-pvc
  storageClassName: local-storage
  path: /app-data
  pvpath: /app-data
  accessModes:
    type: "ReadWriteOnce"

resources:
  requests:
    memory: 250Mi
    cpu: 50m
  limits:
    memory: 500Mi
    cpu: 250m

secrets:
  enabled: false
  name: frontend-sec

configmaps:
  enabled: false

env:
  MYSQL_ROOT_PASSWORD: main_key
  MYSQL_PASSWORD: user_key
  MYSQL_USER: username
  MYSQL_DATABASE: db_name


probes:
  enabled: false
  readinessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 120
    periodSeconds: 10
  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 120
    periodSeconds: 10

initscript:
  enabled: false
  name: flask-init
