{{- if .Values.serviceAccount.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.serviceAccount.name }}-rb
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  apiGroup: ""
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.serviceAccount.name }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}}