{{- if .Values.secrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.secrets.name }}
  labels: {{ include "mylabels" . | nindent 4 }}
type: Opaque
data:
  main_key: MYSQL_ROOT_PASS
  user_key: MYSQL_USER_PASS
  username: MYSQL_USER
  db_name: MYSQL_DATABASE
{{- end -}}